export const quotes = 
[
    "Impressive taste in music!",
    "Your musical taste is amazing!",
    "Your taste in music is excellent!",
    "Wow, your music taste is fantastic!",
    "Incredible taste in music, truly.",
    "Your music taste is on point!",
    "Exceptional taste in music!",
    "You've got exceptional taste in music!",
    "Outstanding taste in music!",
    "Your musical taste is outstanding!",
    "Wow, your taste in music is exceptional!",
    "You have exceptional taste in music!",
    "Your taste in music is top-notch!",
    "Spectacular taste in music!",
    "Your musical taste is spectacular!",
    "Absolutely fantastic taste in music!",
    "Wow, your taste in music is superb!",
    "Great choice! Your taste in music is superb!",
    "Your taste in music is sublime!",
    "Impressive, your taste in music is sublime!",
    "You have an amazing taste in music!",
    "Superb taste in music, truly!",
    "Your music taste is superb!",
    "Your musical taste is brilliant!",
    "Brilliant taste in music, indeed!",
    "Incredible, your taste in music is brilliant!",
    "Your taste in music is divine!",
    "Wow, your musical taste is divine!",
    "Your taste in music is outstanding, truly!",
    "Fantastic! Your taste in music is outstanding.",
    "Your taste in music is unmatched!",
    "Incredible, your taste in music is unmatched!",
    "You've got unmatched taste in music!",
    "Your musical taste is unmatched!",
    "Your taste in music is impeccable!",
    "Impeccable taste in music, indeed!",
    "Wow, your taste in music is impeccable!",
    "You have impeccable taste in music!",
    "Your taste in music is unparalleled!",
    "Incredible, your taste in music is unparalleled!",
    "Your taste in music is exceptional, no doubt!",
    "Exceptional! Your taste in music is top-notch.",
    "Your musical taste is unparalleled!",
    "Your taste in music is extraordinary!",
    "Incredible, your taste in music is extraordinary!",
    "Wow, you've got extraordinary taste in music!",
    "Your taste in music is exquisite!",
    "Exquisite taste in music, truly!",
    "Impressive! Your taste in music is exquisite.",
    "Your musical taste is exquisite!",
    "Your taste in music is unmatched, truly!",
    "Wow, your taste in music is unmatched!",
    "Your taste in music is superb, no doubt!",
    "Your musical taste is exceptional!",
    "Exceptional taste in music, indeed!",
    "Outstanding! Your taste in music is exceptional.",
    "Your taste in music is extraordinary, truly!",
    "Extraordinary taste in music, indeed!",
    "Wow, your taste in music is extraordinary!",
    "Your taste in music is superbly exceptional!",
    "Your taste in music is phenomenal!",
    "Phenomenal taste in music, indeed!",
    "Wow, your taste in music is phenomenal!",
    "Your taste in music is divine, no doubt!",
    "Your musical taste is divine!",
    "Divine taste in music, indeed!",
    "Impressive! Your taste in music is divine.",
    "Your taste in music is impeccable, no doubt!",
    "Impeccable taste in music, indeed!",
    "Wow, your taste in music is impeccable!",
    "Your taste in music is sublime, no doubt!",
    "Sublime taste in music, indeed!",
    "Incredible! Your taste in music is sublime.",
    "Your taste in music is extraordinary, no doubt!",
    "Incredible taste in music, indeed!",
    "Wow, your taste in music is extraordinary!",
    "Your taste in music is top-notch, no doubt!",
    "Your musical taste is top-notch!",
    "Top-notch taste in music, indeed!",
    "Impressive! Your taste in music is top-notch.",
    "Your taste in music is outstandingly exceptional!",
    "Your taste in music is truly remarkable!",
    "Wow, your taste in music is truly remarkable!",
    "Your musical taste is truly remarkable!",
    "Your taste in music is phenomenal, no doubt!",
    "Phenomenal taste in music, indeed!",
    "Wow, your taste in music is phenomenal!",
    "Your taste in music is unmatched, no doubt!",
    "Unmatched taste in music, indeed!",
    "Incredible! Your taste in music is unmatched.",
    "Your taste in music is spectacularly exceptional!",
    "Your taste in music is superbly outstanding!",
    "Wow, your taste in music is superbly outstanding!",
    "Your taste in music"
];